tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   1 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   1 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start giver wallet 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start 5  0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start giver wallet 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start GIVER WALLET 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start   0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start GIVER WALLET 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
tonlib-opencl-cli -v 3  -C global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty 0 512'
./miner/tonlib-cuda-cli -v 3  -C ./miner/global.config.json -e 'pminer start    512'
./miner/tonlib-cuda-cli -v 3  -C ./miner/global.config.json -e 'pminer start kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN EQCnsdU_xP2p6hq7IxAi9eKSoHk4QwxTYuZjAG7YkI48w-Ty  512'
./miner/tonlib-cuda-cli -v 3  -C ./miner/global.config.json -e 'pminer start    512'
./miner/tonlib-cuda-cli -v 3  -C ./miner/global.config.json -e 'pminer start kf-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMHJ8 EQBLjYCi0D1uQ7mEGU2kSip3FsYafsCJJUw2ho99-JoO_vfX  512'
./miner/tonlib-cuda-cli -v 3  -C ./miner/global.config.json -e 'pminer start kf-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMHJ8 EQBLjYCi0D1uQ7mEGU2kSip3FsYafsCJJUw2ho99-JoO_vfX  512'
./miner/tonlib-cuda-cli -v 3  -C ./miner/global.config.json -e 'pminer start kf-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMHJ8 EQBLjYCi0D1uQ7mEGU2kSip3FsYafsCJJUw2ho99-JoO_vfX  512'
